### ISSUE TITLE
Not able to install GeoIP2::Database::Reader

### ISSUE THREAD

**Issue by laxminarayanp** [maxmind/GeoIP2-perl#58]
Not able install GeoIP2::Database::Reader perl module on rhel 6 server. tried cpan/cpanm etc.
Multiple Maxmind modules getting failed during the install process and at the end it says Bailing out the installation for GeoIP2-2.004000.

Installed perl version is 5.10.1.

It will be great help if someone shed some light on this issue.

Regards,
Lakshminarayanan

**Comment by oschwald** [comment]
There isn't much to go on. Would you be able to provide the `build.log` from the `cpanm` install?

**Comment by laxminarayanp** [comment]
Thank for responding, oschwald. Please see the attached.

[build.log.txt.log](https://github.com/maxmind/GeoIP2-perl/files/1633231/build.log.txt.log)

**Comment by oschwald** [comment]
Glancing at your log file, it looks like some dependencies are failing to be installed due to `gcc` not being available. This library is supposed to be installable without any XS dependencies and I would consider this a bug. However, if you can, you may be able to work around it by installing basic build tools. I don't use RHEL, but something like `yum groupinstall 'Development Tools'` may work.

**Comment by laxminarayanp** [comment]
thanks oschwald for checking it and suggesting. I will try what you've suggested and update.

**Comment by laxminarayanp** [comment]
Able to resolve this after installing multiple dependencies.

Thank you Oschwald.
