### ISSUE TITLE
Deprecation notice does not specify what the alternative is

### ISSUE THREAD

**Issue by robrwo** [maxmind/GeoIP2-perl#75]
Under the SUPPORT section it now says that the module is deprecated. But it does not say what should be used instead.

**Comment by oschwald** [comment]
This package will continue to work and we will supply fixes for any significant bugs. However, we are no longer adding new features or support for new outputs to our Perl APIs due to limited usage. If you are reading MMDB databases, using https://github.com/maxmind/MaxMind-DB-Reader-perl directly might be more prudent. We use it internally and unlike this higher level library, it doesn't need to be updated to provide access to new outputs or new database types.

**Comment by incognico** [comment]
> using https://github.com/maxmind/MaxMind-DB-Reader-perl directly might be more prudent.

Well, it seems MaxMind::DB::Reader is deprecated too.

**Comment by robrwo** [comment]
But you've still not added a note in the documentation saying what to use as an alternative.

If you're going to deprecate something, then you need to explicitly state somewhere in the documentation why it's deprecated, and what to use instead.

**Comment by oschwald** [comment]
This library is no longer receiving active development. Unfortunately, the usage of our Perl libraries was extremely low and we could no longer commit to maintaining them at the level our libraries for other languages receive. I do not know of another Perl library with a comparable set of features.

As mentioned in the documentation, this library will continue to receive security fixes as well as fixes for major bugs. We are however not updating it for new outputs or more minor issues. Despite being deprecated as well, `MaxMind::DB::Reader` does not need to be updated to access new outputs and we do use it internally.
